---
title: "Publications"
---

## Papers in journals

- BIAZOLI, L. ; **OLIVEIRA, I. R. C.** Impacts of the COVID-19 pandemic on health insurance in southeastern Brazil: an interrupted time series analysis. *SIGMAE*, 2024.

- ZARZAR, CARLOS ANTÔNIO ; FERNANDES, T. J. ; **OLIVEIRA, I. R. C.** . Modeling the growth of Pacific white shrimp (Litopenaeus vannamei) using the new Bayesian hierarchical approach based on correcting bias caused by incomplete or limited data. *Ecological Informatics*, v. x, p. 102271, 2023.[doi](http://dx.doi.org/10.1016/j.ecoinf.2023.102271)

- PEREIRA, CARINE R. ; NEIA, RAQUEL C. ; SILVA, SAULO B. ; WILLIAMSON, CHARLES H.D. ; GILLECE, JOHN D. ; O'CALLAGHAN, DAVID ; FOSTER, JEFFREY T. ; **OLIVEIRA, IZABELA R.C.** ; BUENO FILHO, JÚLIO S.S. ; LAGE, ANDREY P. ; AZEVEDO, VASCO A.C. ; DORNELES, ELAINE M.S. . Comparison of Brucella abortus population structure based on genotyping methods with different levels of resolution. *JOURNAL OF MICROBIOLOGICAL METHODS*, v. 211, p. 106772, 2023. [doi](http://dx.doi.org/10.1016/j.mimet.2023.106772)

- SANTOS, P. R. ; **OLIVEIRA, I. R. C. **; FREIRE, E. R. C. G. . O pacote Shiny na criação de applets para o ensino de Funções Matemáticas e Estatística Descritiva na Educação Básica. *PROFESSOR DE MATEMÁTICA ONLINE*, v. 10, p. 65-75, 2022.

- INÁCIO, MONIQUE LOUISE CASSIMIRO ; PEREIRA, FERNANDA COSTA ; FERNANDES, LIDIANE BATISTA ; **OLIVEIRA, IZABELA REGINA CARDOSO DE **; PEREIRA, RAFAELA CORRÊA ; DE ANGELIS-PEREIRA, MICHEL CARDOSO . Food and Nutrition Education Using Intuitive Method and NOVA Food Classification: Implications for Food Practices of Children and Adolescents Intuitive Method in Food and Nutrition Education. *AMERICAN JOURNAL OF HEALTH PROMOTION*, v. 0-, p. 089011712210923, 2022.[doi](http://dx.doi.org/10.1177/08901171221092394)

- ZARZAR, CARLOS ANTÔNIO ; SILVA, EDILSON MARCELINO ; FERNANDES, TALES JESUS ; **DE OLIVEIRA, IZABELA REGINA CARDOSO **. Evidence of parameters underestimation from nonlinear growth models for data classified as limited. *COMPUTERS AND ELECTRONICS IN AGRICULTURE*, v. 200, p. 107196, 2022.[doi](http://dx.doi.org/10.1016/j.compag.2022.107196)

- LOURENÇÃO, LUIZ FELIPE DE PAIVA ; DE PAULA, NARA CRISTINA ; CARDOSO, MARIA ANGÉLICA ; SANTOS, PAULA RIBEIRO ; **DE OLIVEIRA, IZABELA REGINA CARDOSO** ; FONSECA, FERNANDO LUIZ AFFONSO ; DA VEIGA, GLAUCIA LUCIANO ; ALVES, BEATRIZ DA COSTA AGUIAR ; GRACIANO, MIRIAM MONTEIRO DE CASTRO ; PEREIRA-DOURADO, STELA MÁRCIA . Biochemical markers and anthropometric profile of children enrolled in public daycare centers. *Jornal de Pediatria*, v. 98, p. 390-398, 2022. [doi](http://dx.doi.org/10.1016/j.jped.2021.09.006)

- **OLIVEIRA, I.R.C.** ; FERREIRA, D. F. . Computing the noncentrality parameter to the distribution of the square of the sample multiple correlation coefficient. *CHILEAN JOURNAL OF STATISTICS*, v. 13, p. 187-199, 2022. [doi](http://dx.doi.org/10.32372/chjs.13-02-04)

- GANDIA, R. M. ; ANTONIALLI, F. ; OLIVEIRA, J. R. ; SUGANO, J. Y. ; NICOLAI, I. ; **OLIVEIRA, I.R.C.** . Willingness to use MaaS in a developing country. *International Journal of Transport Development and Integration*, v. 5, p. 57-68, 2021.

- INACIO, M. L. C. ; PEREIRA, F. C. ; ALMEIDA, I. C. ; FERNANDES, L. B. ; GARCIA, D. S. ; SILVA, T. A. F. ; PEREIRA, K. A. C. ; **OLIVEIRA, I. R. C. **; PEREIRA, R. C. ; PEREIRA, M. C. A. . Caracterização de crianças e adolescentes vulneráveis residentes de uma cidade Sulmineira. *SAÚDE E DESENVOLVIMENTO HUMANO*, v. 9, p. 1-9, 2021. [doi](http://dx.doi.org/10.18316/sdh.v9i2.7074)

- GANDIA, R. M. ; ANTONIALLI, F. ; NICOLAI, I. ; SUGANO, J. Y. ; OLIVEIRA, J. R. ; **OLIVEIRA, I. R. C.** . Casual Carpooling: A Strategy to Support Implementation of Mobility-as-a-Service in a Developing Country. *Sustainability*, v. 13, p. 2774, 2021. [doi](http://dx.doi.org/10.3390/su13052774)

- LOURENCAO, L. F. P. ; GRACIANO, M. M. C. ; SANTOS, P. R. ; **OLIVEIRA, I.R.C.** ; PEREIRA, S. M. . Intervenção educativa em sau-de nutricional para educadores infantis da rede pública: um estudo avaliativo. *PRÁXIS EDUCACIONAL (ONLINE)*, v. 17, p. 1-22, 2021. [doi](http://dx.doi.org/10.22481/praxisedu.v17i46.8426)

- DORNELES, ELAINE MARIA SELES ; OLIVEIRA, M. M. ; PEREIRA, C. R. ; **OLIVEIRA, I.R.C. **; GODFROID, J. ; LAGE, A. P. . Efficacy of *Brucella abortus* S19 and RB51 vaccine strains: A systematic review and meta-analysis. *Transboundary and Emerging Diseases*, p. 1-19, 2021. [doi](http://dx.doi.org/10.1111/tbed.14259)

- LOURENCAO, L. F. P. ; SANTOS, P. R. ; **OLIVEIRA, I. R. C.** ; FONSECA, F. L. A. ; DRAGHI, P. F. ; GRACIANO, M. M. C. ; PEREIRA, S. M. . Socioeconomic factors related to food consumption and the condition of food and nutrition insecurity in preschoolers. *NUTRIRE - REVISTA DA SOCIEDADE BRASILEIRA DE ALIMENTAÇÃO E NUTRIÇÃO*, v. 46, p. 1, 2021.

- PEREIRA, CARINE RODRIGUES ; COTRIM DE ALMEIDA, JOÃO VITOR FERNANDES ; **CARDOSO DE OLIVEIRA, IZABELA REGINA**; FARIA DE OLIVEIRA, LUCIANA ; PEREIRA, LUCIANO JOSÉ ; ZANGERÔNIMO, MÁRCIO GILBERTO ; LAGE, ANDREY PEREIRA ; DORNELES, ELAINE MARIA SELES . Occupational exposure to Brucella spp.: a systematic review and meta-analysis. *PLoS Neglected Tropical Diseases*, v. 14, p. e0008164, 2020. [doi](http://dx.doi.org/10.1371/journal.pntd.0008164)

- PEREIRA, CARINE RODRIGUES ; **DE OLIVEIRA, IZABELA REGINA CARDOSO **; DE OLIVEIRA, LUCIANA FARIA ; DE OLIVEIRA, CAMILA STEFANIE FONSECA ; LAGE, ANDREY PEREIRA ; DORNELES, ELAINE MARIA SELES . Accidental exposure to vaccines and occupational brucellosis among veterinarians in Minas Gerais state, Brazil. *Transboundary and Emerging Diseases*, v. 00, p. 1-14, 2020. [doi](http://dx.doi.org/10.1111/tbed.13797)

- DOMINGUES, J. M. ; MIRANDA, V. F. L. ; REZENDE, D. C. ; LARES, Y. S. ; FERREIRA, S. R. ; **OLIVEIRA, I.R.C. **. Statistical Modeling on Quarrying Activities and its Impact on Resident?s Satisfaction. *Journal of Environmental Science and Sustainable Development*, v. 3, p. 416-429, 2020. [doi](http://dx.doi.org/10.7454/jessd.v3i2.1062)

- OLIVEIRA, CARLOS DELANO CARDOSO DE ; **OLIVEIRA, IZABELA REGINA CARDOSO DE **; SUGANUMA, MARCIO SEIJI ; DURIGAN, GISELDA . Overstory trees in excess: A threat to restoration success in Brazilian Atlantic forest. *FOREST ECOLOGY AND MANAGEMENT*, v. 449, p. 117453, 2019.[doi](http://dx.doi.org/10.1016/j.foreco.2019.117453)

- PAREIRA, R. T. ; NEBO, C. ; NAVES, L. P. ; FORTES-SILVA, R. ; **OLIVEIRA, I.R.C. **; PAULINO, R. R. ; DRUMMOND, C. D. ; ROSA, P.V. . Distribution of goblet and endocrine cells in the intestine: a comparative study in Amazonian freshwater tambaqui and hybrid catfish. *Journal of Morphology*, v. 281, p. 55-67, 2019. [doi](http://dx.doi.org/10.1002/jmor.21079)

- **OLIVEIRA, I. R. C. **; MOLENBERGHS, G. ; VERBEKE, G. ; DEMETRIO, C. G. B. ; DIAS, C. T. S. . Negative variance components for non-negative hierarchical data with correlation, over-, and/or underdispersion. *JOURNAL OF APPLIED STATISTICS*, v. 44, p. 1047-1063, 2017. [doi](http://dx.doi.org/10.1080/02664763.2016.1191624)

- ANDRADE, M. C. ; SILVA, A. A. ; NEIVA, I. P. ; **OLIVEIRA, I. R. C.** ; CASTRO, E. M. ; FRANCIS, D. M. ; MALUF, W. R. . Inheritance of type IV glandular trichome density and its association with whitefly resistance from Solanum galapagense accession LA1401. *EUPHYTICA*, v. 213, p. 1, 2017. [doi](http://dx.doi.org/10.1007/s10681-016-1792-1)

- NUNES, M. H. ; TERRA, M. ; **OLIVEIRA, I. R. C.** ; VAN DEN BERG, E. . The influence of disturbance on driving carbon stocks and tree dynamics of riparian forests in Cerrado. *Journal of Plant Ecology*, v. 000000, p. 1, 2017. [doi](http://dx.doi.org/10.1093/jpe/rtx007)

- PEREIRA, R. T. ; FREITAS, T. R. ; **OLIVEIRA, I. R. C.** ; COSTA, L. S. ; VIGLIANO, F. A. ; ROSA, P.V. . Endocrine cells producing peptide hormones in the intestine of Nile tilapia: distribution and effects of feeding and fasting on the cell density. *FISH PHYSIOLOGY AND BIOCHEMISTRY*, v. 000000, p. 1-14, 2017.[doi](http://dx.doi.org/10.1007/s10695-017-0380-1)

- **OLIVEIRA, I.R.C.**; MOLENBERGHS, G. ; DEMETRIO, C. G. B. ; DIAS, C. T. S. ; GIOLO, S. ; ANDRADE, M. C. . Quantifying intraclass correlations for count and time-to-event data. *Biometrical Journal*, 2016.[doi](http://dx.doi.org/10.1002/bimj.201500093)

- PEREIRA, R.T. ; COSTA, L.S. ; **OLIVEIRA, I.R.C. **; ARAÚJO, J.C. ; AERTS, M. ; VIGLIANO, F.A. ; ROSA, P.V. . Relative distribution of gastrin- CCK-8-, NPY- and CGRP-immunoreactive cells in the digestive tract of dorado (Salminus brasiliensis). *Tissue & Cell*, v. 00, p. 01, 2015.[doi](http://dx.doi.org/10.1016/j.tice.2015.01.009)

- **OLIVEIRA, I. R. C.** ; Rezende, M. T. ; DIAS, C. T. S. ; GOMES, D. S. ; BOTREL, E. P. ; GOMES, L. A. A. . Evaluation of crisphead lettuce cultivars in different cover types by manova and discriminant analysis. *Horticultura Brasileira*, v. 31, p. 439-444, 2013.[doi](http://dx.doi.org/10.1590/s0102-05362013000300015)

- **OLIVEIRA, I. R. C.** ; FERREIRA, D. F. . Avaliação da probabilidade de classificação incorreta em análises discriminantes para duas populações normais. *Sigmae*, v. 2, p. 1, 2013.

- **Oliveira, Izabela Regina Cardoso** ; Ferreira, Daniel Furtado . Computing the noncentral gamma distribution, its inverse and the noncentrality parameter. *Computational Statistics (Zeitschrift)*, v. 28, p. 1663-1680, 2012.[doi](http://dx.doi.org/10.1007/s00180-012-0371-8)

- **Cardoso De Oliveira, I.R. **; FERREIRA, D. F. . Multivariate extension of chi-squared univariate normality test. *Journal of Statistical Computation and Simulation (Print)*, v. 80, p. 513-526, 2010.[doi](http://dx.doi.org/10.1080/00949650902731377)

## Papers in proceedings of conferences

-	GANDIA, R. M. ; OLIVEIRA, J. R. ; ANTONIALLI, F. ; PATRICIO, L. B. ; SUGANO, J. Y. ; NICOLAI, I. ; **OLIVEIRA, I. R. C.** . Casual Carpooling as an Strategy to Implement Mobility-as-a-Service (MaaS) in a Developing Country, 2019, Paris. Paradigm shift? The Automotive Industry in Transition, 2019.

-	GANDIA, R. M. ; OLIVEIRA, J. R. ; ANTONIALLI, F. ; SUGANO, J. Y. ; NICOLAI, I. ; **OLIVEIRA, I.R.C. **. Consumer Predisposition and Behavior Towards Mobility-as-a-Service among University Students in a Developing Country, 2019, Aveiro. Urban Transport 2019, 2019. p. 163-174.

-	**OLIVEIRA, I. R. C.** ; MOLENBERGHS, G. ; VERBEKE, G. ; DEMETRIO, C. G. B. ; DIAS, C. T. S. . Negative Variance Components for Nonnegative Hierarchical Data, 2015, Presidente Pudente. Anais da 60a Reunião Anual da Região Brasileira da Sociedade Inernacional de Biometria e 16o Simpósio de Estatística aplicada à Experimentação Agronômica, 2015.

-	NUNES, M. H. ;**OLIVEIRA, I. R. C.** ; KANIESKI - SILVA, B. ; NICOLETTI, M. F. ; CARVALHO, S. P. C. . Continuidade espacial de características dendrométricas em uma área de cerrado no norte de Goiás, 2011, Santa Maria. Anais do 5º Simpósio Latino-Americano sobre Manejo Florestal, 2011. v. 5. p. 170-177.